apiVersion: apps/v1
kind: Deployment

metadata:
  name: interiorvision-frontend

spec:
  replicas: 2

  strategy:
    type: RollingUpdate

  selector:
    matchLabels:
      app: interiorvision-frontend

  template:
    metadata:
      labels:
        app: interiorvision-frontend

    spec:
      containers:
        - name: frontend
          image: kahboh/shoesly-frontend:v1
          ports:
            - containerPort: 80